howto:
	$(info ***********************)
	$(info This is a python code, so we do not need to compile anything.)
	$(info Run the code as the following:)
	$(info )
	$(info $$ python rules.py -s min_support -c min_conf > output.txt)
	$(info )
	$(info Or you can run using the default values $$ python rules.py > output.txt)
	$(info )
	$(info e.g.)
	$(info $$ python rules.py -s 0.02 -c 0.2 > output.txt)
	$(info ***********************)
	exit 
